exchange:
  {
    "logger_name": "dtl",
    "log_file_path": "data/Logs/message.log",
    "config_path": "config/dtl.cfg",
  }
strategy:
  {
    "order_refresh_time": 10,
    "order_amount": 100,
  }

tick_size: 1
