exchange:
  {
    "logger": {
      "verbose": True,
      "name": "dtl",
      "path": "data/Logs/message.log",
    },
    "config_path": "config/dtl.cfg",
    "order_lifespan": 300, #seconds
    "refresh_time": 180,
  }
strategy:
  {
    "order_amount": 100,
    "refresh_time": 0.1,
    "max_n_orders": 1000,
    "max_run_time": 600,
  }
tick_size: 0.1
